const text = [
  `Curabitur feugiat rutrum tellus, quis condimentum risus efficitur vitae. Aliquam euismod ut leo vel commodo. Donec vel augue sollicitudin, pharetra diam a, sagittis nulla. Donec a felis risus. Phasellus aliquam interdum erat, in lacinia urna pretium a. Mauris vitae nisi quis lorem ullamcorper dictum. Morbi quis diam ut leo finibus faucibus. Vestibulum at imperdiet mauris. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Donec id tristique ligula. Phasellus sit amet interdum velit. Aenean sit amet ipsum dolor. Nunc commodo, orci vitae dapibus eleifend, magna ipsum euismod ipsum, eget rutrum orci elit id ligula. Nullam cursus condimentum augue quis porttitor. Aliquam et ligula lobortis, rhoncus tortor at, porttitor est. Vivamus vitae dui sed orci volutpat pulvinar non a dui. Suspendisse ultricies rhoncus justo at mollis. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Nam a sollicitudin diam. Nullam blandit augue in elit hendrerit sagittis. Sed sed erat iaculis turpis auctor egestas. Nullam eget lacus sodales, egestas dolor a, aliquam tellus. Nunc nibh ante, interdum ac eros et, semper molestie dolor. Sed pulvinar, ligula dignissim efficitur congue, arcu tortor malesuada felis, in efficitur risus lectus sed felis. Etiam rutrum quam nulla, at luctus ex ornare ut. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Vivamus ultrices bibendum finibus. Vivamus accumsan commodo ante in lacinia. Suspendisse auctor odio non ligula euismod, ut molestie lorem lobortis. Nam lacinia, est ac sollicitudin fringilla, diam nisl placerat nulla, sit amet aliquet leo nisl quis metus. Quisque id lobortis nisl, sit amet blandit orci. Donec porta tristique urna, et malesuada neque facilisis ac. Vivamus ultricies laoreet tortor, sit amet lobortis neque accumsan eget. Quisque molestie rutrum libero non cursus. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Nulla nec efficitur dui. Integer id risus nisl. Etiam convallis metus in magna tincidunt, non convallis leo viverra. Nullam at ex sed nisl rutrum vestibulum. Cras faucibus felis ipsum, vitae ultrices urna scelerisque id. Aliquam erat volutpat. Pellentesque arcu dui, ultricies a mollis eu, ultrices eu lacus. Etiam vestibulum magna vitae fringilla fermentum. Nunc a rhoncus felis, id facilisis ligula. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Fusce metus eros, mollis vitae nisl id, dictum efficitur nulla. Donec rutrum vestibulum augue gravida tincidunt. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam dictum neque ac purus consectetur, eget fermentum leo tempus. Praesent vehicula vitae magna volutpat venenatis. Vivamus et elementum magna. Suspendisse euismod libero porta, sagittis ante eu, aliquet risus. Nullam aliquet, lorem at molestie ullamcorper, tellus magna egestas dolor, sed ornare augue enim tristique augue. Nulla laoreet eget sapien in consequat. Nullam fermentum rhoncus ipsum laoreet pharetra. Vivamus luctus urna in magna malesuada tincidunt. Integer quis libero in turpis ornare tincidunt. Suspendisse et quam sed purus varius euismod. Sed ultricies pharetra diam, volutpat consequat nisi laoreet eget. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Mauris id laoreet urna. Etiam sed odio mauris. Quisque vitae justo eu tortor ultricies luctus nec nec neque. Suspendisse euismod, enim eget egestas lacinia, diam nisi rutrum justo, sit amet tristique quam elit ac ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis a ex dapibus, congue mi eget, molestie libero. Morbi imperdiet porta ornare. Quisque ac elementum ante. In porta ipsum sit amet nibh molestie, ac elementum urna dictum. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Sed a nisi lacus. Duis ornare ullamcorper ante eu condimentum. Donec laoreet justo et erat ultricies faucibus id consequat dui. Aliquam eget velit aliquet, sollicitudin justo eu, rhoncus mauris. Duis lorem sem, dapibus ut pellentesque quis, congue eu ligula. Sed varius erat eget euismod cursus. Ut dictum consectetur euismod. Mauris ut efficitur elit. Nulla urna arcu, interdum vel libero quis, hendrerit iaculis lorem. Quisque eu massa quis turpis sodales facilisis nec at ligula. Curabitur in sapien sed nisl molestie auctor. Nam vehicula sed massa in posuere. Integer ullamcorper auctor sem eu imperdiet. Sed quis malesuada mi. Phasellus ut lacinia elit. Proin sollicitudin, enim vel rhoncus fermentum, neque elit gravida augue, nec tempor enim magna vel arcu. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Maecenas fringilla lacinia augue, et finibus justo semper nec. Proin sit amet dui a leo condimentum sollicitudin quis eget turpis. Donec eu sagittis purus. Vivamus aliquam, turpis in hendrerit bibendum, magna quam luctus felis, vel sodales libero sapien non mauris. Phasellus id ipsum eget risus rhoncus maximus non at lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis quis ante dolor. Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit.`,
  `Praesent orci est, dapibus in eleifend eu, tincidunt vel nisi. Aliquam a ipsum magna. Duis commodo tortor turpis, eget ullamcorper ipsum posuere placerat. Pellentesque non nunc vel erat semper viverra. Vestibulum vehicula nulla in leo porta placerat. Etiam convallis imperdiet facilisis. Nam dictum arcu sit amet mi luctus, id fermentum lorem finibus. Vivamus scelerisque elit nec enim efficitur accumsan. Quisque gravida eget sapien ut aliquam. Fusce pulvinar augue sed massa malesuada tincidunt. Ut elit leo, suscipit at ligula eu, dignissim ultricies sapien. In at rutrum ligula. Quisque imperdiet mi in lorem lobortis blandit. Quisque eget pretium lorem. Proin laoreet est a rutrum luctus. Quisque fringilla porta dui at egestas. Sed accumsan, quam ac consectetur ornare, nunc neque fermentum neque, vel vulputate libero tellus id quam. Phasellus faucibus eros dolor, vehicula feugiat risus accumsan et. Maecenas dignissim mauris ac nibh rhoncus iaculis. Curabitur faucibus ipsum a sagittis lobortis. Etiam maximus, lorem lobortis porta fermentum, neque sem tempus ante, in mattis sapien nunc et leo. Vestibulum elementum aliquam magna non laoreet.`,
];
const form = document.getElementById("lorem-form");
const count = document.getElementById("num");
const result = document.querySelector(".lorem-text");

form.addEventListener("submit", function (e) {
  e.preventDefault();
  const value = parseInt(count.value);
  const random = Math.floor(Math.random() * text.length);
  if (isNaN(value) || value < 0 || value > 10) {
    result.innerHTML = `<p>${text[random]}<p>`;
  } else {
    let temp = text.slice(0, value);
    temp = temp
      .map(function (item) {
        return `<p>${item}<p/>`;
      })
      .join("");
    result.innerHTML = temp;
  }
});
